export const categoriesConst = {
  smartphones: require("../assets/images/smartphones.webp"),
  laptops: require("../assets/images/laptops.webp"),
  fragrances: require("../assets/images/fragrances.webp"),
  skincare: require("../assets/images/skincare.webp"),
  groceries: require("../assets/images/groceries.webp"),
  "home-decoration": require("../assets/images/home-decoration.webp"),
  furniture: require("../assets/images/furniture.webp"),
  tops: require("../assets/images/tops.webp"),
  "womens-dresses": require("../assets/images/womens-dresses.webp"),
  "womens-shoes": require("../assets/images/womens-shoes.webp"),
  "mens-shirts": require("../assets/images/mens-shirts.webp"),
  "mens-shoes": require("../assets/images/mens-shoes.webp"),
  "mens-watches": require("../assets/images/mens-watches.webp"),
  "womens-watches": require("../assets/images/womens-watches.webp"),
  "womens-bags": require("../assets/images/womens-bags.webp"),
  "womens-jewellery": require("../assets/images/womens-jewellery.webp"),
  sunglasses: require("../assets/images/sunglasses.webp"),
  automotive: require("../assets/images/automotive.webp"),
  motorcycle: require("../assets/images/motorcycle.webp"),
  lighting: require("../assets/images/lighting.webp"),
};
